# -*- coding: utf-8 -*-
"""DecisionTree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BwdmWAB3DskVrW_q-gEEnOm0VA_YMp1D
"""

import pandas as pd
import numpy as np
df=pd.read_csv(r"/content/diabetes.csv")
df.head(5)

df.info()

df.describe()

df.isnull().sum()

df.shape

qu=df.groupby(["Age"])["Pregnancies"].sum()
qu

import matplotlib.pyplot as plt
qu.plot(kind="bar")
plt.show()

x=df.drop("Outcome",axis=1)
y=df["Outcome"]
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split



x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42)
model=DecisionTreeClassifier()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

from sklearn.tree import export_graphviz
import graphviz

graphviz.Source(export_graphviz(model,feature_names=x.columns,filled=True))

